# Generated by Django 5.2.3 on 2025-06-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs_service', '0002_alter_documentshare_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='documentshare',
            options={'verbose_name': 'Shared Document', 'verbose_name_plural': 'Shared Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(blank=True, help_text='Stores rich text content (e.g., Quill.js or Tiptap JSON structure)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(help_text='The creator of the document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='Whether the shared user can edit the document'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(help_text='The document being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='srs_service.document'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='shared_with',
            field=models.ForeignKey(help_text='The user this document is shared with', on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
